apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    name: todo-app
    project: todo-app
    managed-by: backstage-template
    created-by: backstage
  annotations:
    backstage.io/project-name: "todo-app"
spec: {}
