apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifact-registry
  namespace: zeta
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .mysecret | toString }}"
    name: artifact-registry
    creationPolicy: Owner
  data:
  - secretKey: mysecret
    remoteRef:
      key: artifactory-registry-sa-json
