apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/managed-by: backstage-template
    project: todo-app
    created-by: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: ./app-of-apps/
    repoURL: git@github.com:Arpit-Sharma-at-Appointy/idp-demo.git
    targetRevision: HEAD
  sources: []
  project: idp-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
